name: Static Data Detection

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  static-data-check:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        
    - name: Install dependencies
      run: |
        npm ci
        cd frontend && npm ci
        cd ../backend && npm ci
        
    - name: Run static data detection
      run: |
        chmod +x scripts/check-static-data.js
        node scripts/check-static-data.js
        
    - name: Comment PR with results
      if: failure() && github.event_name == 'pull_request'
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: `## ❌ Static Data Detection Failed
            
            Your PR contains hardcoded/static data that violates our dynamic data policy.
            
            **Required Actions:**
            - Remove all hardcoded arrays and mock data
            - Replace with dynamic API calls
            - Ensure all data comes from database/context
            - Add proper loading states
            
            **Checklist:**
            - [ ] No static data arrays
            - [ ] All data fetched from APIs
            - [ ] Proper error handling
            - [ ] Loading states implemented
            
            Please fix these issues and push your changes to re-run the check.`
          })
